create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  customer_name text not null check (char_length(customer_name) between 1 and 100),
  phone text not null check (char_length(phone) between 7 and 40),
  service text not null check (char_length(service) between 1 and 120),
  preferred_date date not null,
  message text check (message is null or char_length(message) <= 1000),
  locale text not null default 'zh' check (char_length(locale) between 2 and 10),
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

create index if not exists appointments_created_at_idx
  on public.appointments (created_at desc);

create index if not exists appointments_preferred_date_idx
  on public.appointments (preferred_date);

create table if not exists public.staff_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  display_name text not null
    check (char_length(display_name) between 1 and 80),
  role text not null default 'operator'
    check (role in ('admin', 'operator')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users (id) on delete set null
);

create unique index if not exists staff_profiles_email_idx
  on public.staff_profiles (lower(email));

create table if not exists public.operator_account_history (
  id bigint generated by default as identity primary key,
  operator_id uuid not null
    references public.staff_profiles (id) on delete restrict,
  action text not null
    check (action in ('created', 'deleted')),
  acted_by uuid not null
    references public.staff_profiles (id) on delete restrict,
  acted_at timestamptz not null default now()
);

create index if not exists operator_account_history_operator_idx
  on public.operator_account_history (operator_id, acted_at desc);

insert into public.staff_profiles (
  id,
  email,
  display_name,
  role
)
select
  id,
  email,
  coalesce(
    nullif(raw_user_meta_data ->> 'display_name', ''),
    split_part(email, '@', 1)
  ),
  'admin'
from auth.users
where email is not null
order by created_at
limit 1
on conflict (id) do nothing;

insert into public.operator_account_history (
  operator_id,
  action,
  acted_by,
  acted_at
)
select
  operator.id,
  'created',
  coalesce(operator.created_by, admin.id),
  operator.created_at
from public.staff_profiles as operator
cross join lateral (
  select id
  from public.staff_profiles
  where role = 'admin'
  order by created_at
  limit 1
) as admin
where operator.role = 'operator'
  and not exists (
    select 1
    from public.operator_account_history as history
    where history.operator_id = operator.id
      and history.action = 'created'
  );

alter table public.appointments
  add column if not exists status_changed_by uuid
    references public.staff_profiles (id) on delete set null;

alter table public.appointments
  add column if not exists status_changed_at timestamptz;

create table if not exists public.appointment_status_history (
  id bigint generated by default as identity primary key,
  appointment_id uuid not null
    references public.appointments (id) on delete cascade,
  from_status text not null
    check (from_status in ('pending', 'confirmed', 'completed', 'cancelled')),
  to_status text not null
    check (to_status in ('pending', 'confirmed', 'completed', 'cancelled')),
  changed_by uuid not null
    references public.staff_profiles (id) on delete restrict,
  changed_at timestamptz not null default now()
);

create index if not exists appointment_status_history_appointment_idx
  on public.appointment_status_history (appointment_id, changed_at desc);

create or replace function public.is_active_staff(
  check_user uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.staff_profiles
    where id = check_user
      and active
  );
$$;

create or replace function public.is_admin(
  check_user uuid default auth.uid()
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.staff_profiles
    where id = check_user
      and active
      and role = 'admin'
  );
$$;

revoke all on function public.is_active_staff(uuid) from public;
revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_active_staff(uuid) to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;

create or replace function public.record_appointment_status_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor uuid := auth.uid();
begin
  if new.status is distinct from old.status then
    if actor is null or not public.is_active_staff(actor) then
      raise exception 'Only active staff can change appointment status';
    end if;

    new.status_changed_by := actor;
    new.status_changed_at := now();

    insert into public.appointment_status_history (
      appointment_id,
      from_status,
      to_status,
      changed_by,
      changed_at
    )
    values (
      old.id,
      old.status,
      new.status,
      actor,
      new.status_changed_at
    );
  end if;

  return new;
end;
$$;

drop trigger if exists record_appointment_status_change
  on public.appointments;

create trigger record_appointment_status_change
  before update of status on public.appointments
  for each row
  execute function public.record_appointment_status_change();

alter table public.appointments enable row level security;
alter table public.staff_profiles enable row level security;
alter table public.appointment_status_history enable row level security;
alter table public.operator_account_history enable row level security;

drop policy if exists "Anyone can submit an appointment" on public.appointments;
create policy "Anyone can submit an appointment"
  on public.appointments
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Authenticated admins can view appointments" on public.appointments;
drop policy if exists "Active staff can view appointments" on public.appointments;
create policy "Active staff can view appointments"
  on public.appointments
  for select
  to authenticated
  using (public.is_active_staff());

drop policy if exists "Authenticated admins can update appointments" on public.appointments;
drop policy if exists "Active staff can update appointments" on public.appointments;
create policy "Active staff can update appointments"
  on public.appointments
  for update
  to authenticated
  using (public.is_active_staff())
  with check (public.is_active_staff());

drop policy if exists "Active staff can view staff profiles"
  on public.staff_profiles;
create policy "Active staff can view staff profiles"
  on public.staff_profiles
  for select
  to authenticated
  using (public.is_active_staff());

drop policy if exists "Active staff can view status history"
  on public.appointment_status_history;
create policy "Active staff can view status history"
  on public.appointment_status_history
  for select
  to authenticated
  using (public.is_active_staff());

drop policy if exists "Admins can view operator account history"
  on public.operator_account_history;
create policy "Admins can view operator account history"
  on public.operator_account_history
  for select
  to authenticated
  using (public.is_admin());

revoke all on table public.appointments from anon, authenticated;
revoke all on table public.staff_profiles from anon, authenticated;
revoke all on table public.appointment_status_history from anon, authenticated;
revoke all on table public.operator_account_history from anon, authenticated;
grant insert (
  customer_name,
  phone,
  service,
  preferred_date,
  message,
  locale
) on table public.appointments to anon, authenticated;
grant select on table public.appointments to authenticated;
grant update (status) on table public.appointments to authenticated;
grant select on table public.staff_profiles to authenticated;
grant select on table public.appointment_status_history to authenticated;
grant select on table public.operator_account_history to authenticated;

comment on table public.appointments is
  'Customer booking requests submitted through the ORA website.';

comment on table public.staff_profiles is
  'Administrator and operator accounts allowed to access booking management.';

comment on table public.appointment_status_history is
  'Immutable audit log for every booking status change.';

comment on table public.operator_account_history is
  'Immutable audit log for operator account creation and deletion.';
