begin;

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null
    references public.customers (id) on delete restrict,
  user_id uuid not null
    references auth.users (id) on delete restrict,
  status text not null default 'active'
    check (status in ('active', 'expired', 'cancelled', 'refunded')),
  complimentary_service_code text not null
    check (complimentary_service_code in ('pure-reset', 'vital-glow')),
  complimentary_redeemed_at timestamptz,
  complimentary_redeemed_checkout_id uuid
    references public.checkouts (id) on delete restrict,
  price_cents integer not null default 28800
    check (price_cents = 28800),
  currency text not null default 'USD'
    check (currency = 'USD'),
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '1 year'),
  provider_payment_id text not null unique,
  payment_environment text not null
    check (payment_environment in ('sandbox', 'production')),
  receipt_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at > starts_at)
);

create unique index if not exists memberships_one_active_per_user_idx
  on public.memberships (user_id)
  where status = 'active';

create index if not exists memberships_customer_idx
  on public.memberships (customer_id, expires_at desc);

create index if not exists memberships_expiry_idx
  on public.memberships (status, expires_at);

create table if not exists public.membership_events (
  id bigint generated by default as identity primary key,
  membership_id uuid not null
    references public.memberships (id) on delete cascade,
  event_type text not null
    check (
      event_type in (
        'purchased',
        'complimentary_redeemed',
        'cancelled',
        'refunded'
      )
    ),
  checkout_id uuid references public.checkouts (id) on delete restrict,
  details jsonb not null default '{}',
  acted_by uuid references public.staff_profiles (id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists membership_events_membership_idx
  on public.membership_events (membership_id, created_at desc);

alter table public.checkouts
  add column if not exists membership_id uuid
    references public.memberships (id) on delete restrict,
  add column if not exists membership_discount_cents integer not null default 0
    check (membership_discount_cents >= 0),
  add column if not exists membership_complimentary_applied boolean
    not null default false;

alter table public.checkout_items
  add column if not exists membership_discount_cents integer not null default 0
    check (membership_discount_cents >= 0),
  add column if not exists membership_complimentary_applied boolean
    not null default false;

create or replace function public.redeem_membership_benefit_on_checkout_paid()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  redeemed_membership_id uuid;
begin
  if new.status = 'paid'
    and old.status is distinct from 'paid'
    and new.membership_complimentary_applied
    and new.membership_id is not null then
    update public.memberships
    set
      complimentary_redeemed_at = coalesce(new.closed_at, now()),
      complimentary_redeemed_checkout_id = new.id,
      updated_at = now()
    where id = new.membership_id
      and status = 'active'
      and expires_at > now()
      and complimentary_redeemed_at is null
    returning id into redeemed_membership_id;

    if redeemed_membership_id is null then
      raise exception 'Complimentary membership benefit is unavailable';
    end if;

    insert into public.membership_events (
      membership_id,
      event_type,
      checkout_id,
      details,
      acted_by
    )
    values (
      new.membership_id,
      'complimentary_redeemed',
      new.id,
      jsonb_build_object(
        'membership_discount_cents',
        new.membership_discount_cents
      ),
      new.closed_by
    );
  end if;

  return new;
end;
$$;

drop trigger if exists redeem_membership_benefit_on_checkout_paid
  on public.checkouts;

create trigger redeem_membership_benefit_on_checkout_paid
after update of status on public.checkouts
for each row
execute function public.redeem_membership_benefit_on_checkout_paid();

alter table public.memberships enable row level security;
alter table public.membership_events enable row level security;

drop policy if exists "Customers and staff can view memberships"
  on public.memberships;
drop policy if exists "Customers and staff can view membership events"
  on public.membership_events;

create policy "Customers and staff can view memberships"
  on public.memberships for select to authenticated
  using (
    user_id = auth.uid()
    or public.is_active_staff()
  );

create policy "Customers and staff can view membership events"
  on public.membership_events for select to authenticated
  using (
    exists (
      select 1
      from public.memberships membership
      where membership.id = membership_events.membership_id
        and (
          membership.user_id = auth.uid()
          or public.is_active_staff()
        )
    )
  );

revoke all on table public.memberships from anon, authenticated;
revoke all on table public.membership_events from anon, authenticated;

grant select on table public.memberships to authenticated;
grant select on table public.membership_events to authenticated;

comment on table public.memberships is
  'ORA Annual Membership purchases and benefit state.';
comment on column public.memberships.complimentary_service_code is
  'One-time complimentary service selected at purchase: pure-reset or vital-glow.';
comment on column public.checkouts.membership_discount_cents is
  'Server-calculated membership discount included in discount_cents.';

commit;
